#define MINORCYCLEPERSEC 100
#define HALFHZCOUNT MINORCYCLEPERSEC / 2
#define HALFHZDELAY HALFHZCOUNT / 2
#define 2HZCOUNT MINORCYCLEPERSEC * 2
#define 2HZDELAY 2HZCOUNT / 2
#define MAJORCYCLECOUNT MINORCYCLEPERSEC * 4
