#define MINORCYCLEPERSEC 100
#define HALFHZCOUNT MINORCYCLEPERSEC / 2
#define HALFHZDELAY HALFHZCOUNT / 2
#define T1HZCOUNT MINORCYCLEPERSEC * 2
#define T1HZDELAY MINORCYCLEPERSEC / 2
#define T2HZCOUNT MINORCYCLEPERSEC * 2
#define T2HZDELAY T2HZCOUNT / 2
#define MAJORCYCLECOUNT MINORCYCLEPERSEC * 5
